#!/usr/bin/env ruby

require "topobook"

# Takes a PDF file as input, then processes it into SVG for
# processing into smaller, more usable SVG images for manipulation

pdf_file = ARGV[0]
export_dir = File.basename(pdf_file, ".pdf")
svg_file = File.join(export_dir, "#{File.basename(pdf_file, ".pdf")}.svg")
svg_noimg_file = File.join(export_dir, "#{File.basename(svg_file, ".svg")}-noimg.svg")
optimized_svg = File.join(export_dir, "#{File.basename(svg_noimg_file, ".svg")}-opt.svg")

Dir.mkdir(export_dir) unless Dir.exist?(export_dir)

puts "Converting PDF to SVG"
puts `pdf2svg #{pdf_file} #{svg_file}`

puts "Extracting embedded images"
Topobook::ExtractSvgImages.new(svg_file, svg_noimg_file, File.join(export_dir, "images")).extract

puts "Making optimized master SVG #{optimized_svg}"
puts `svgo -i #{svg_noimg_file} -o #{optimized_svg}`
